version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.9.21-management-alpine
    restart: unless-stopped
    ports:
    - 5672:5672
    - 15672:15672

  redis:
    image: redis:7.0.4-alpine
    restart: unless-stopped
    ports:
    - 6379:6379

  recepcionist:
    build: .
    restart: unless-stopped
    command: go run ./src/main.go --recepcionist
    depends_on:
    - rabbitmq
    - redis
    volumes:
    - .:/app:ro
    ports:
    - 8085:8080

  specialist:
    build: .
    restart: unless-stopped
    command: go run ./src/main.go --specialist
    depends_on:
    - rabbitmq
    - redis
    volumes:
    - .:/app:ro